### ISSUE TITLE
Quick Opener is throwing errors on plugin Use System Desktop Plugin: 1.0.2

### ISSUE THREAD

**Issue by manikantannaren** [Chris2011/QuickOpener-NetBeans#19]
https://github.com/manikantannaren/mynetbeans/issues/35
Environment:
Product Version: Apache NetBeans IDE 11.2
Java: 12; OpenJDK 64-Bit Server VM 12+33
Runtime: OpenJDK Runtime Environment 12+33
System: Mac OS X version 10.14.6 running on x86_64; UTF-8; en_IN (nb)

Steps to reproduce
1. Start Apache NetBeans 11.2 with Java 12
2. Navigate to Tools | Plugins
3. Click Available Plugins tab
4. Install NetBeans Use System Desktop plugin
5. Install QuickOpener plugin

Soon after install and every start of the IDE 4 warning dialogs show up
### Warnings
![image](https://user-images.githubusercontent.com/5435047/69696178-e0f64a00-1104-11ea-9027-dfc14d884bc8.png)

### Error log
```Caused: org.openide.filesystems.FSException: Cannot create file Actions because Loaders/Desktop/org-pr-nb-plugins-usd-MailWithSystem.shadow on filesystem Default System is not a folder.
	at org.openide.filesystems.MultiFileObject.createFolder(MultiFileObject.java:1078)
	at org.openide.filesystems.FileUtil.createFolder(FileUtil.java:702)
[catch] at me.dsnet.quickopener.Installer$ActionInstaller.handleFileType(Installer.java:67)
	at me.dsnet.quickopener.Installer$FileTypeHandler.run(Installer.java:53)
	at org.netbeans.core.windows.WindowManagerImpl$Exclusive$1.run(WindowManagerImpl.java:1615)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
ALL [null]: Cannot create file Actions because Loaders/Desktop/org-pr-nb-plugins-usd-MailWithSystem.shadow on filesystem Default System is not a folder.```

Should you need more information, please let me know.

**Comment by manikantannaren** [comment]
Forgot mention "Even though the warnings appear, it does not affect functionality"

**Comment by Chris2011** [comment]
Hi,

thx for the report. I can try to fix it, but I'm not for having 2 or 3 or more plugins, which makes the same. It would be great, if you can contribute code, what you are missing in my plugin, to it, instead of having your own. What do you think?


Cheers

Chris

**Comment by patacra** [comment]
Hi,

Thanks @manikantannaren for having found that it appears with the `Netbeans Use System Desktop` plugin from the *Base IDE* category. In the meanwhile, I simply desactivated this plugin so that `QuickOpener` could run without these multiple error message boxes at the startup. But I think the best would be to uninstall it as its functionnalities are mostly covered by `QuickOpener`.

Patrick

**Comment by Chris2011** [comment]
Thx @patacra to catching this up. And if everything is missing in QuickOpener, please feel free to create a ticket and maybe a PR too if possible :)
